// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  Address,
  DataSourceTemplate,
  DataSourceContext
} from "@graphprotocol/graph-ts";

export class Pool extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("Pool", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext("Pool", [address.toHex()], context);
  }
}

export class Hypervisor extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("Hypervisor", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "Hypervisor",
      [address.toHex()],
      context
    );
  }
}

export class SteerContract extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("SteerContract", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "SteerContract",
      [address.toHex()],
      context
    );
  }
}
